### ISSUE TITLE
Including hashlookup expansion in graphoscope

### ISSUE THREAD

**Issue by adulau** [cert-lv/graphoscope#2]
What would be the best way to integrate [hashlookup](https://circl.lu/services/hashlookup/) in graphoscope. Not sure if there is a kind of skeleton to extend graphoscope or a documentation somewhere on how to do it properly?

**Comment by aleksejsv** [comment]
As it will be a new and unique data source - a new plugin should be created, which knows how to connect, query and interpret the response.

It seems that with `hashlookup` you will do special HTTP queries, so existing general HTTP https://github.com/cert-lv/graphoscope/tree/master/plugins/src/http and Pastelyzer https://github.com/cert-lv/graphoscope/tree/master/plugins/src/pastelyzer plugins might be the examples for you.

Then a built-in documentation (Web GUI top-right `Options` => `Administration` => `Plugins development`) will show a step-by-step workflow on how to create a new plugin, based on a Template https://github.com/cert-lv/graphoscope/tree/master/plugins/src/template

**Comment by aleksejsv** [comment]
@adulau , do you need help with plugin development? If you share your current code and ideas - we can work on it together

**Comment by gallypette** [comment]
Hi all, 
You can find the current state of this plugin [here](https://github.com/gallypette/graphoscope/tree/hashlookup)
Here is what it looks like ATM:
![graphoscope](https://user-images.githubusercontent.com/329725/165331352-70a3ca14-0ca3-47e5-a8f5-ee765c8fe5a2.png)

**Comment by aleksejsv** [comment]
@gallypette , I've checked plugin's code. Can you please send a pull request so I can add comments and questions?

**Comment by aleksejsv** [comment]
New `hashlookup` plugin was added.
