### ISSUE TITLE
Setting cacheTTL does not seem to have any effect

### ISSUE THREAD

**Issue by gallypette** [cert-lv/graphoscope#5]
HI all,
When writing plugins, it's useful to launch the same search again and again but the cache hinders the progression.
I am not sure it behaves consistently, I tried to lower the `cacheTTL` in `graphoscope.yaml` or set it to 0 to no avail.

Is there a way to disable the cache altogether or to shorten its TTL to close to zero?

**Comment by aleksejsv** [comment]
Hello!

According to the MongoDB documentation their expired documents cleaning routine doesn't remove documents instantly, but is being executed once per 60 seconds by default.

I tried to set `cacheTTL: 5` and documents in `cache` collection disappeared after around 20 seconds. Theoretically it means that when document is expired - we can wait additionally up to 59 seconds.

Does it work for you in the same way?

Also when you start the service a line `DBG Cache coll's index is created` should appear without errors.

---

However, probably you still don't want to wait a minute after every request. What do you think if I add the additional checks `if cacheTTL == 0` and if it's **True** - do not query/set cache. Will it be the best solution for you?

**Comment by gallypette** [comment]
Oh yes, having the possibility to completely disable would be the best.

**Comment by aleksejsv** [comment]
Implemented this. Please try the latest version.
Enabled cache `cacheTTL` can't be less than 60, set to 0 to disable.

**Comment by gallypette** [comment]
thank you ;)
