### ISSUE TITLE
Graph limits

### ISSUE THREAD

**Issue by gallypette** [cert-lv/graphoscope#7]
Hi,

I am implementing the `LIMIT` feature for hashlookup and it looks like the graph cannot display much elements by default.
`HASHLOOKUP has too many results, add filters manually or use the charts (based on limited data) to reduce the amount of returned data. Or close the charts to see the possible data from the other sources`

Is there a way to set a higher value ?

**Comment by aleksejsv** [comment]
In `graphoscope.yaml` there is `limit: 1000` by default - you can increase the value and restart the service. But even 1000 graph nodes are a lot for the naked eye, make sure your graph image makes sense.

One thing about implementing plugin's `LIMIT` - this is something that should affect the amount of requested data, literally like in SQL. You will configure it for your own user in Web GUI settings -> Profile. By default there is `Limit: 0`, which means **no limit**.
